[build]
  base = "photography-booking-app"
  command = "npm i --no-fund --no-audit && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  DEBUG = "vite:*,rollup:*"
  VITE_LOG_LEVEL = "info"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
