# /netlify.toml
[build]
  base = "photography-booking-app"
  command = "npm i --no-fund --no-audit && npm run build"
  publish = "dist"

# Make directory relative to the base above
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
