# netlify.toml  (root of repo)
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Let React Router handle all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# If you use serverless functions later (e.g., /api/zip)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  
[build.environment]
SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"
