# netlify.toml (root of repo)

[build]
  command = "npm ci && npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# SPA fallback (fine even with hash routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: friendly alias for functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "20"
