[build]
  # Your app lives in this subfolder:
  base = "photography-booking-app"
  command = "npm ci && npm run build"
  publish = "dist"

# Only keep this block if you actually have functions in this folder.
[functions]
  directory = "photography-booking-app/netlify/functions"
  node_bundler = "esbuild"

# SPA fallback (keeps deep links working)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
